# Generated by Django 5.0 on 2024-01-18 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='train_seat',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='train.seat'),
        ),
        migrations.AddField(
            model_name='booking',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='train.train'),
        ),
    ]
