# Generated by Django 5.0 on 2024-01-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='train',
        ),
    ]
