# Generated by Django 5.0 on 2024-01-23 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_train'),
        ('train', '0014_rename_price_train_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='train.train'),
        ),
    ]
