# Generated by Django 5.0 on 2024-01-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_train_seat_booking_seat_booking_train'),
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainSeat',
        ),
    ]
