# Generated by Django 5.0 on 2024-01-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_station_remove_train_station_train_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
