# Generated by Django 5.0 on 2024-01-23 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0006_trainfare_trainseat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='station',
        ),
        migrations.AddField(
            model_name='train',
            name='from_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_station', to='train.station'),
        ),
        migrations.AddField(
            model_name='train',
            name='to_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_station', to='train.station'),
        ),
    ]
