# Generated by Django 5.0 on 2024-01-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0008_remove_train_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='departure',
            field=models.TimeField(),
        ),
    ]
