# Generated by Django 5.0 on 2024-01-23 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0009_alter_train_departure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='compartment',
        ),
    ]
