# Generated by Django 5.0 on 2024-01-23 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0010_remove_seat_compartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainseat',
            old_name='is_available',
            new_name='is_booked',
        ),
    ]
