# Generated by Django 5.0 on 2024-01-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0011_rename_is_available_trainseat_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
