# Generated by Django 5.0 on 2024-01-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0013_delete_trainfare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='price',
            new_name='ticket_price',
        ),
    ]
