# Generated by Django 5.0 on 2024-01-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0017_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='train/media/uploads/'),
        ),
    ]
