# Generated by Django 5.0 on 2024-01-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='admin_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
